### ISSUE TITLE
java.lang.Exception: DeviceHelper.getAdvertiseID call on main thread!!

### ISSUE THREAD

**Issue by enjoy2000** [tiendung01023/zalo_flutter#12]
Flutter version:

```
Flutter (Channel stable, 3.16.5, on macOS 13.5.1 22G90 darwin-arm64, locale en-VN)
```

```
E/getAdvertiseID(30585): java.lang.Exception: DeviceHelper.getAdvertiseID call on main thread!!
E/getAdvertiseID(30585): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/getAdvertiseID(30585): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/getAdvertiseID(30585): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/getAdvertiseID(30585): 	at android.os.Looper.loopOnce(Looper.java:201)
E/getAdvertiseID(30585): 	at android.os.Looper.loop(Looper.java:288)
E/getAdvertiseID(30585): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/getAdvertiseID(30585): 	at java.lang.reflect.Method.invoke(Native Method)
E/getAdvertiseID(30585): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/getAdvertiseID(30585): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Got this error randomly with the `login` function? Any ideas how to fix it?

**Comment by tiendung01023** [comment]
When the error occurs, can you log in?

**Comment by enjoy2000** [comment]
can I think 😕 
I didn't work on that any more tho
